using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dinTour.Models;

namespace dinTour.MockData
{
    public class MockParkering
    {
        public static List<Parkering> parkering = new List<Parkering>()
        {
            new Parkering(1, false, 40),
            new Parkering(2, false, 40),
            new Parkering(3, false, 40),
            new Parkering(4, false, 40),
            new Parkering(5, false, 40),
            new Parkering(6, false, 40),
            new Parkering(7, false, 40),
            new Parkering(8, false, 40),
            new Parkering(9, false, 40),
            new Parkering(10, false, 40),
            new Parkering(11, false, 40),
            new Parkering(12, false, 40),
            new Parkering(13, false, 40),
            new Parkering(14, false, 40),
            new Parkering(15, false, 40),
            new Parkering(16, false, 40),
            new Parkering(17, false, 40),
            new Parkering(18, false, 40),
            new Parkering(19, false, 40),
            new Parkering(20, false, 40),
            new Parkering(21, false, 40),
            new Parkering(22, false, 40),
            new Parkering(23, false, 40),
            new Parkering(24, false, 40),
            new Parkering(25, false, 40),
            new Parkering(26, false, 40),
            new Parkering(27, false, 40),
            new Parkering(28, false, 40),
            new Parkering(29, false, 40),
            new Parkering(30, false, 40),
            new Parkering(31, false, 40),
            new Parkering(32, false, 40),
            new Parkering(33, false, 40),
            new Parkering(34, false, 40),
            new Parkering(35, false, 40),
            new Parkering(36, false, 40),
            new Parkering(37, false, 40),
            new Parkering(38, false, 40),
            new Parkering(39, false, 40),
            new Parkering(40, false, 40),
            new Parkering(41, false, 40),
            new Parkering(42, false, 40),
            new Parkering(43, false, 40),
            new Parkering(44, false, 40),
            new Parkering(45, false, 40),
            new Parkering(46, false, 40),
            new Parkering(47, false, 40),
            new Parkering(48, false, 40),
            new Parkering(49, false, 40),
            new Parkering(50, false, 40),
            new Parkering(51, false, 40),
            new Parkering(52, false, 40),
            new Parkering(53, false, 40),
            new Parkering(54, false, 40),
            new Parkering(55, false, 40),
            new Parkering(56, false, 40),
            new Parkering(57, false, 40),
            new Parkering(58, false, 40),
            new Parkering(59, false, 40),
            new Parkering(60, false, 40),
            new Parkering(61, false, 40),
            new Parkering(62, false, 40),
            new Parkering(63, false, 40),
            new Parkering(64, false, 40),
            new Parkering(65, false, 40),
            new Parkering(66, false, 40),
            new Parkering(67, false, 40),
            new Parkering(68, false, 40),
            new Parkering(69, false, 40),
            new Parkering(70, false, 40),
            new Parkering(71, false, 40),
            new Parkering(72, false, 40),
            new Parkering(73, false, 40),
            new Parkering(74, false, 40),
            new Parkering(75, false, 40),
            new Parkering(76, false, 40),
            new Parkering(77, false, 40),
            new Parkering(78, false, 40),
            new Parkering(79, false, 40),
            new Parkering(80, false, 40),
            new Parkering(81, false, 40),
            new Parkering(82, false, 40),
            new Parkering(83, false, 40),
            new Parkering(84, false, 40),
            new Parkering(85, false, 40),
            new Parkering(86, false, 40),
            new Parkering(87, false, 40),
            new Parkering(88, false, 40),
            new Parkering(89, false, 40),
            new Parkering(90, false, 40)
        };
        public static List<Parkering> GetMockParkering()
        {
            return parkering;
        }
    }
}
